using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using NUnit.Framework;
using Renci.SshNet;
using Renci.SshNet.Security;
using SshNet.Keygen.Extensions;

namespace SshNet.Keygen.Tests
{
    public class TestKey
    {
        private void KeyGenTest<T>(SshKeyInfo keyInfo)
        {
            for (int i = 0; i < 3; i++)
            {
                var key = SshKey.Generate(keyInfo);
                if (keyInfo.KeyLength != 0)
                    Assert.AreEqual(keyInfo.KeyLength, (key.KeyLength));

                var privateKey = key.ToOpenSshFormat("Generated by SshNet.Keygen");
                var publicKey = key.ToOpenSshPublicFormat("Generated by SshNet.Keygen");
                TestContext.WriteLine($"Run: {i}");
                TestContext.WriteLine(privateKey);
                TestContext.WriteLine(publicKey);

                // File.WriteAllText("test-key", privateKey);
                // File.WriteAllText("test-key.pub", publicKey);

                var keyFile = new PrivateKeyFile(privateKey.ToStream());
                Assert.IsInstanceOf<T>(((KeyHostAlgorithm) keyFile.HostKey).Key);
                if (keyInfo.KeyLength != 0)
                    Assert.AreEqual(keyInfo.KeyLength, (((KeyHostAlgorithm) keyFile.HostKey).Key.KeyLength));
            }
        }

        [Test]
        public void GenerateED25519Key()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.ED25519
            };
            KeyGenTest<ED25519Key>(keyInfo);
        }

        [Test]
        public void GenerateRSA2048()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.RSA,
                KeyLength = 2048
            };
            KeyGenTest<RsaKey>(keyInfo);
        }

        [Test]
        public void GenerateRSA3072()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.RSA,
                KeyLength = 3072
            };
            KeyGenTest<RsaKey>(keyInfo);
        }

        [Test]
        public void GenerateRSA4096()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.RSA,
                KeyLength = 4096
            };
            KeyGenTest<RsaKey>(keyInfo);
        }

        [Test]
        public void GenerateRSA8192()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.RSA,
                KeyLength = 8192
            };
            KeyGenTest<RsaKey>(keyInfo);
        }

        [Test]
        public void GenerateEcdsa256()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.ECDSA,
                KeyLength = 256
            };
            KeyGenTest<EcdsaKey>(keyInfo);
        }

        [Test]
        public void GenerateEcdsa384()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.ECDSA,
                KeyLength = 384
            };
            KeyGenTest<EcdsaKey>(keyInfo);
        }

        [Test]
        public void GenerateEcdsa521()
        {
            var keyInfo = new SshKeyInfo
            {
                KeyType = KeyType.ECDSA,
                KeyLength = 521
            };
            KeyGenTest<EcdsaKey>(keyInfo);
        }

        private string GetKey(string keyname)
        {
            var resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(string.Format("SshNet.Keygen.Tests.TestKeys.{0}", keyname));
            using (var reader = new StreamReader(resourceStream, Encoding.ASCII))
            {
                return reader.ReadToEnd();
            }
        }

        private void TestFormatKey<T>(string keyname, int keyLength)
        {
            var keydata = GetKey(keyname);
            var pubkeydata = GetKey($"{keyname}.pub");
            var fpMd5Data = GetKey($"{keyname}.fingerprint.md5");
            var fpSha1Data = GetKey($"{keyname}.fingerprint.sha1");
            var fpSha256Data = GetKey($"{keyname}.fingerprint.sha256");
            var fpSha384Data = GetKey($"{keyname}.fingerprint.sha384");
            var fpSha512Data = GetKey($"{keyname}.fingerprint.sha512");
            var keyFile = new PrivateKeyFile(keydata.ToStream());
            var key = ((KeyHostAlgorithm) keyFile.HostKey).Key;

            Assert.IsInstanceOf<T>(key);
            Assert.AreEqual(keyLength, key.KeyLength);
            Assert.AreEqual(pubkeydata.Trim(), keyFile.ToOpenSshPublicFormat().Trim());
            Assert.AreEqual(fpSha256Data.Trim(), keyFile.Fingerprint().Trim());
            Assert.AreEqual(fpMd5Data.Trim(), keyFile.Fingerprint(HashAlgorithmName.MD5).Trim());
            Assert.AreEqual(fpSha1Data.Trim(), keyFile.Fingerprint(HashAlgorithmName.SHA1).Trim());
            Assert.AreEqual(fpSha256Data.Trim(), keyFile.Fingerprint(HashAlgorithmName.SHA256).Trim());
            Assert.AreEqual(fpSha384Data.Trim(), keyFile.Fingerprint(HashAlgorithmName.SHA384).Trim());
            Assert.AreEqual(fpSha512Data.Trim(), keyFile.Fingerprint(HashAlgorithmName.SHA512).Trim());

            // XXX: We cannot test the result of the PrivateKey Export, since Random CheckInts are random...
            //      So just check the key can be reimport again.
            // Assert.AreEqual(keydata.Trim(), keyFile.ToOpenSshFormat().Trim());
            Assert.DoesNotThrow(() =>
            {
                new PrivateKeyFile(key.ToOpenSshFormat().ToStream());
            });
        }

        [Test]
        public void TestRSA2048()
        {
            TestFormatKey<RsaKey>("RSA2048", 2048);
        }

        [Test]
        public void TestRSA3072()
        {
            TestFormatKey<RsaKey>("RSA3072", 3072);
        }

        [Test]
        public void TestRSA4096()
        {
            TestFormatKey<RsaKey>("RSA4096", 4096);
        }

        [Test]
        public void TestRSA8192()
        {
            TestFormatKey<RsaKey>("RSA8192", 8192);
        }

        [Test]
        public void TestECDSA256()
        {
            TestFormatKey<EcdsaKey>("ECDSA256", 256);
        }

        [Test]
        public void TestECDSA384()
        {
            TestFormatKey<EcdsaKey>("ECDSA384", 384);
        }

        [Test]
        public void TestECDSA521()
        {
            TestFormatKey<EcdsaKey>("ECDSA521", 521);
        }

        [Test]
        public void TestED25519()
        {
            TestFormatKey<ED25519Key>("ED25519", 256);
        }
    }
}